
POST http://localhost:3002/api/albums HTTP/1.1
Content-Type: application/json 

{
  "id": "",
  "album": "One Size Fits All - test PUT",
  "artist": "Frank Zappa",
  "genre": "Rock/Experimental",
  "important": true
}
