
POST http://localhost:3002/api/albums HTTP/1.1
Content-Type: application/json 

{
  "id": "",
  "album": "One Size Fits All",
  "artist": "Frank Zappa - test : POST - after refactor frontend/build 2",
  "genre": "Rock/Experimental",
  "important": true
}
