PUT http://localhost:3002/api/albums/67606540f399570ef8db0743 HTTP/1.1
Content-Type: application/json 

{
  "id": "",
  "album": "One Size Fits All - test PUT - new : true",
  "artist": "Frank Zappa",
  "genre": "Rock/Experimental",
  "important": true
}
